version: '3.9'
services:
  patient-postgres:
    image: postgres:14.2
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_DB: "patient"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-test} -d patient"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  patient-service:
    depends_on:
      patient-postgres:
        condition: service_healthy

    build:
      context: .
      dockerfile: Patient-Service/Dockerfile
    ports:
      - "5051:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging

networks:
  default:
    name: swsp
